/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MetaPicture {
  coverType: string
  mimeType?: string
  description?: string
  data: Uint8Array
  constructor(mime: string, data: Uint8Array, desc?: string | undefined | null)
}

export declare class MusicTagger {
  constructor()
  /** Load music file from buffer */
  loadBuffer(buffer: Uint8Array): void
  /**
   * Load music file from file path
   *
   * Invalid in wasm
   */
  loadPath(path: string): void
  /** Drop current file */
  dispose(): void
  /** Check if current file is disposed */
  isDisposed(): boolean
  /** Save changes to buffer */
  saveBuffer(): void
  /**
   * Save changes to file path
   *
   * Invalid in wasm
   */
  savePath(path?: string | undefined | null): void
  /**
   * Get buffer
   * Make sure run `save()` before
   */
  get buffer(): Uint8Array
  /** Audio file quality */
  get quality(): Quality
  /** Audio bit depth in bits */
  get bitDepth(): number | null
  /**
   * Audio bit rate in kbps
   *
   * Note: If the audio property not available,
   * the getter will try to calculates an approximate bitrate including metadata size.
   */
  get bitRate(): number | null
  /** Audio sample rate in Hz */
  get sampleRate(): number | null
  /** Number of channels */
  get channels(): number | null
  /** Duration in milliseconds */
  get duration(): number
  /** File's tag type */
  get tagType(): string | null
  /** The title of the music file */
  get title(): string | null
  set title(title: string)
  /** The artist of the music file */
  get artist(): string | null
  set artist(artist: string)
  /** The album of the music file */
  get album(): string | null
  set album(album: string)
  /** The year of the music file */
  get year(): number | null
  set year(year: number)
  /** The genre of the music file */
  get genre(): string | null
  set genre(genre: string)
  /** The track number of the music file */
  get trackNumber(): number | null
  set trackNumber(trackNumber: number)
  /** The disc number of the music file */
  get discNumber(): number | null
  set discNumber(discNumber: number)
  /** The total number of tracks */
  get trackTotal(): number | null
  set trackTotal(trackTotal: number)
  /** The total number of discs */
  get discsTotal(): number | null
  set discsTotal(discsTotal: number)
  /** The comment of the music file */
  get comment(): string | null
  set comment(comment: string)
  /** The Album Artist of the music file */
  get albumArtist(): string | null
  set albumArtist(albumArtist: string)
  /** The Composer of the music file */
  get composer(): string | null
  set composer(composer: string)
  /** The Conductor of the music file */
  get conductor(): string | null
  set conductor(conductor: string)
  /** The Lyricist of the music file */
  get lyricist(): string | null
  set lyricist(lyricist: string)
  /** The Publisher of the music file */
  get publisher(): string | null
  set publisher(publisher: string)
  /** The lyrics of the music file */
  get lyrics(): string | null
  set lyrics(lyrics: string)
  /** The copyright of the music file */
  get copyright(): string | null
  set copyright(copyright: string)
  /** The track replay gain of the music file */
  get trackReplayGain(): number | null
  set trackReplayGain(trackReplayGain: number)
  /** The track replay peak of the music file */
  get trackReplayPeak(): number | null
  set trackReplayPeak(trackReplayPeak: number)
  /** The album replay gain of the music file */
  get albumReplayGain(): number | null
  set albumReplayGain(albumReplayGain: number)
  /** The album replay peak of the music file */
  get albumReplayPeak(): number | null
  set albumReplayPeak(albumReplayPeak: number)
  /** The pictures of the music file */
  get pictures(): Array<MetaPicture> | null
  set pictures(pictures: Array<MetaPicture>)
}

export declare const enum Quality {
  HQ = 0,
  SQ = 1,
  HiRes = 2
}
