/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MetaPicture {
  coverType: string
  mimeType?: string
  description?: string
  data: Uint8Array
  constructor(mime: string, data: Uint8Array, desc?: string | undefined | null)
}

export declare class MusicTagger {
  /**
   * @constructor
   * Creates a new MusicTagger instance
   *
   * The instance starts in an uninitialized state. You must call either
   * `loadBuffer()` (Browser) or `loadPath()` (Node.js) to load an audio
   * file before using other methods.
   */
  constructor()
  /**
   * Load music file from a byte buffer (dispose the old one before)
   *
   * @param buffer A Uint8Array containing the audio file data
   *
   * @throws If the buffer doesn't contain a valid audio file
   * @throws If the file doesn't contain any metadata tags
   */
  loadBuffer(buffer: Uint8Array): void
  /**
   * Load music file from a file path (dispose the old one before)
   *
   * @param path The file system path to the audio file
   *
   * @throws If the path doesn't exist or isn't accessible
   * @throws If the file doesn't contain a valid audio format
   * @throws If the file doesn't contain any metadata tags
   * @throws If runs in WebAssembly environments (due to file system restrictions).
   */
  loadPath(path: string): void
  /**
   * Dispose of the currently loaded file
   *
   * Releases all resources associated with the loaded audio file.
   * After calling this method, the instance returns to an uninitialized state.
   *
   * @note Any unsaved changes will be lost when disposing.
   */
  dispose(): void
  /**
   * Check if the current file is disposed. Use this method to verify
   * if the instance is ready for operations before calling other methods.
   *
   * @returns `true` if no file is currently loaded, `false` otherwise
   */
  isDisposed(): boolean
  /**
   * Save metadata changes back to the internal buffer
   *
   * @throws If no file or buffer loaded
   * @throws If saving fails due to file format constraints
   */
  save(): void
  /**
   * Current audio file buffer as a `Uint8Array`
   *
   * @throws If no file or buffer loaded
   *
   * @note For files loaded via `loadBuffer()`, call `saveBuffer()` first to ensure
   * metadata changes are applied. For files loaded via `loadPath()`, this
   * returns an empty buffer.
   */
  get buffer(): Uint8Array
  /**
   * Audio quality classification ("HQ", "SQ", or "HiRes")
   *
   * @throws If no file or buffer loaded
   *
   * Quality is determined based on file format, sample rate, and bit depth:
   * - HQ: Lossy formats (MP3, AAC, etc.)
   * - SQ: Lossless formats at CD quality (44.1kHz, 16-bit)
   * - HiRes: Lossless formats exceeding CD quality (>44.1kHz, >=16-bit)
   */
  get quality(): string
  /**
   * Audio bit depth in bits, or `null` if not available
   *
   * @throws If no file or buffer loaded
   *
   * Common values: 16 (CD quality), 24 (Hi-Res), 32 (studio quality)
   */
  get bitDepth(): number | null
  /**
   * Audio bit rate in kbps, or `null` if not available
   *
   * @throws If no file or buffer loaded
   *
   * @note If the audio properties don't provide a bitrate, this method calculates
   * an approximate bitrate based on file size and duration, including metadata.
   * The calculated bitrate is constrained between MIN_BITRATE and MAX_BITRATE.
   */
  get bitRate(): number | null
  /**
   * Audio sample rate in Hz, or `null` if not available
   *
   * @throws If no file or buffer loaded
   *
   * Common values: 44100 (CD), 48000 (DVD), 96000, 192000 (Hi-Res)
   */
  get sampleRate(): number | null
  /**
   * Number of audio channels, or `null` if not available
   *
   * @throws If no file or buffer loaded
   *
   * Common values: 1 (mono), 2 (stereo), 6 (5.1 surround)
   * Common values: 1 (mono), 2 (stereo), 6 (5.1 surround), 8 (7.1 surround)
   */
  get channels(): number | null
  /**
   * Audio duration in seconds, or `null` if not available
   *
   * @throws If no file or buffer loaded
   */
  get duration(): number
  /**
   * File's metadata tag type, or `null` if not recognized
   *
   * Supported tag types: "ID3V1", "ID3V2", "APE", "VORBIS", "MP4", "AIFF", "RIFF"
   *
   * @throws If no file or buffer loaded
   */
  get tagType(): string | null
  /**
   * Title, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get title(): string | null
  set title(title: string | null)
  /**
   * Artist, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get artist(): string | null
  set artist(artist: string | null)
  /**
   * Album, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get album(): string | null
  set album(album: string | null)
  /**
   * Year, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get year(): number | null
  set year(year: number | null)
  /**
   * Genre, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get genre(): string | null
  set genre(genre: string | null)
  /**
   * Track number, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get trackNumber(): number | null
  set trackNumber(trackNumber: number | null)
  /**
   * Disc number, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get discNumber(): number | null
  set discNumber(discNumber: number | null)
  /**
   * Total number of tracks in the album, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get trackTotal(): number | null
  set trackTotal(trackTotal: number | null)
  /**
   * Total number of discs in the album, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get discsTotal(): number | null
  set discsTotal(discsTotal: number | null)
  /**
   * Comment, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get comment(): string | null
  set comment(comment: string | null)
  /**
   * Album artist, or `null` if not set
   *
   * @throws If no file or buffer loaded
   *
   * @note Album artist differs from track artist and represents the primary artist for the entire album.
   */
  get albumArtist(): string | null
  set albumArtist(albumArtist: string | null)
  /**
   * Composer, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get composer(): string | null
  set composer(composer: string | null)
  /**
   * Conductor, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get conductor(): string | null
  set conductor(conductor: string | null)
  /**
   * Lyricist, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get lyricist(): string | null
  set lyricist(lyricist: string | null)
  /**
   * Publisher, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get publisher(): string | null
  set publisher(publisher: string | null)
  /**
   * Lyrics, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get lyrics(): string | null
  set lyrics(lyrics: string | null)
  /**
   * Copyright information, or `null` if not set
   *
   * @throws If no file or buffer loaded
   */
  get copyright(): string | null
  set copyright(copyright: string | null)
  /**
   * Track replay gain in dB, or `null` if not set
   *
   * @throws If no file or buffer loaded
   *
   * @note Replay gain is used to normalize playback volume across different tracks.
   */
  get trackReplayGain(): number | null
  set trackReplayGain(trackReplayGain: number | null)
  /**
   * Track replay peak value, or `null` if not set
   *
   * @throws If no file or buffer loaded
   *
   * @note Replay peak represents the maximum amplitude level in the track.
   */
  get trackReplayPeak(): number | null
  set trackReplayPeak(trackReplayPeak: number | null)
  /**
   * Album replay gain in dB, or `null` if not set
   *
   * @throws If no file or buffer loaded
   *
   * @note Album replay gain normalizes playback volume across different albums.
   */
  get albumReplayGain(): number | null
  set albumReplayGain(albumReplayGain: number | null)
  /**
   * Album replay peak value, or `null` if not set
   *
   * @throws If no file or buffer loaded
   *
   * @note Album replay peak represents the maximum amplitude level in the album.
   */
  get albumReplayPeak(): number | null
  set albumReplayPeak(albumReplayPeak: number | null)
  /**
   * Embedded pictures/album art list, or `null` if no picture is embedded
   *
   * @throws If no file or buffer loaded
   *
   * @note Returns all embedded pictures including album art, artist photos, etc.
   */
  get pictures(): Array<MetaPicture> | null
  set pictures(pictures: Array<MetaPicture> | null)
}
