#!/usr/bin/env bash
# Setup npm trusted publishing (OIDC) for music-tag-native and its sub-packages.
#
# Trusted publishing lets GitHub Actions publish to npm without storing an
# NPM_TOKEN secret.  Run this script ONCE from a machine that is already
# authenticated with `npm login` (or `npm adduser`).
#
# Usage:
#   ./scripts/setup-trusted-publish.sh [--dry-run]
#
# Reference: https://docs.npmjs.com/cli/v11/commands/npm-trust#npm-trust-github

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DRY_RUN=false

# ---------------------------------------------------------------------------
# Parse flags
# ---------------------------------------------------------------------------
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

# Require npm >= 11 for `npm trust github` support.
NPM_VERSION=$(npm --version)
NPM_MAJOR=$(echo "$NPM_VERSION" | cut -d. -f1)
if [[ "$NPM_MAJOR" -lt 11 ]]; then
  echo "ERROR: npm >= 11 is required for trusted publishing support (found $NPM_VERSION)."
  echo "       Run: npm install -g npm@latest"
  exit 1
fi

# Verify the user is logged in.
if ! npm whoami &>/dev/null; then
  echo "ERROR: You are not logged in to npm.  Run: npm login"
  exit 1
fi
NPM_USER=$(npm whoami)
echo "Logged in to npm as: $NPM_USER"

# ---------------------------------------------------------------------------
# Configuration derived from the repository
# ---------------------------------------------------------------------------
GITHUB_OWNER="subframe7536"
GITHUB_REPO="music-tag-native"
WORKFLOW=".github/workflows/CI.yml"

ROOT_PACKAGE=$(jq -r '.name' "$REPO_ROOT/package.json")
NPM_DIR="$REPO_ROOT/npm"

# Collect sub-package names from the npm/ directory (pre-generated by napi-rs).
SUB_PACKAGES=()
if [[ -d "$NPM_DIR" ]]; then
  for pkg_json in "$NPM_DIR"/*/package.json; do
    SUB_PACKAGES+=("$(jq -r '.name' "$pkg_json")")
  done
fi

ALL_PACKAGES=("$ROOT_PACKAGE" "${SUB_PACKAGES[@]}")

# ---------------------------------------------------------------------------
# Print summary
# ---------------------------------------------------------------------------
echo ""
echo "Will configure trusted publishing for the following packages:"
for pkg in "${ALL_PACKAGES[@]}"; do
  echo "  - $pkg"
done
echo ""
echo "GitHub source:  $GITHUB_OWNER/$GITHUB_REPO  workflow: $WORKFLOW"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[dry-run] Skipping actual npm trust github calls."
  echo ""
  echo "Commands that would be run:"
  for pkg in "${ALL_PACKAGES[@]}"; do
    echo "  npm trust github $GITHUB_OWNER $GITHUB_REPO $WORKFLOW --package $pkg"
  done
  exit 0
fi

# ---------------------------------------------------------------------------
# Confirm before proceeding
# ---------------------------------------------------------------------------
read -r -p "Proceed? [y/N] " confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

# ---------------------------------------------------------------------------
# Register each package for trusted publishing
# ---------------------------------------------------------------------------
FAILED=()
for pkg in "${ALL_PACKAGES[@]}"; do
  echo ""
  echo "Configuring: $pkg"
  if npm trust github "$GITHUB_OWNER" "$GITHUB_REPO" "$WORKFLOW" --package "$pkg"; then
    echo "  OK"
  else
    echo "  FAILED"
    FAILED+=("$pkg")
  fi
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
if [[ "${#FAILED[@]}" -eq 0 ]]; then
  echo "All packages configured for trusted publishing successfully."
  echo ""
  echo "You can now remove the NPM_TOKEN secret from the repository."
  echo "The .github/workflows/CI.yml publish job uses OIDC (id-token: write)"
  echo "and publishes with --provenance without requiring a stored token."
else
  echo "The following packages failed:"
  for pkg in "${FAILED[@]}"; do
    echo "  - $pkg"
  done
  exit 1
fi
